import os


fd0 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd1 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd2 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd3 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd4 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd5 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd6 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd7 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd8 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
f0 = open(fd0, "wb+", buffering=0)
f1 = open(fd1, "wb+", buffering=0)
f2 = open(fd2, "wb+", buffering=0)
f3 = open(fd3, "wb+", buffering=0)
f4 = open(fd4, "wb+", buffering=0)
f5 = open(fd5, "wb+", buffering=0)
f6 = open(fd6, "wb+", buffering=0)
f7 = open(fd7, "wb+", buffering=0)
f8 = open(fd8, "wb+", buffering=0)

print("Session 1 Testing that first read returns valid sid...", f1.readline())
print("Session 5 Testing that first read returns valid sid...", f5.readline())
print("Session 6 Testing that first read returns valid sid...", f6.read())
print("Session 3 Testing that first read returns valid sid...", f3.read())
print("Session 2 Testing that first read returns valid sid...", f2.read())
print("Session 7 Testing that first read returns valid sid...", f7.read())
print("Session 0 Testing that first read returns valid sid...", f0.read())
print("Session 8 Testing that first read returns valid sid...", f8.read())
print("Session 4 Testing that first read returns valid sid...", f4.read())


print("Session 5 seek(1,0): 5[]", f5.seek(1,0))
print("Session 5 Writing 'PQhLRe': 5PQhLRe[]", f5.write(b'PQhLRe'))
print("Session 3 seek(0,2): 3[]", f3.seek(0,2))
print("Session 3 Writing 'wbR': 3wbR[]", f3.write(b'wbR'))

print("Session 4 seek(0,2): 4[]", f4.seek(0, 2))
print("Session 4 Writing 'QDU': 4QDU[]", f4.write(b'QDU'))

print("Session 8 seek(1,0): 8[]", f8.seek(1,0))
print("Session 8 Writing 'jpqBGkKT': 8jpqBGkKT[]", f8.write(b'jpqBGkKT'))


print("Session 6 seek(0,2): 6[]", f6.seek(0,2))
print("Session 6 Writing 'lRxhSm': 6lRxhSm[]", f6.write(b'lRxhSm'))
print("Session 2 seek(0,0): [2]", f2.seek(0,0))
print("Session 2 Writing 'VgH': VgH[]", f2.write(b'VgH'))
print("Session 2 seek(2,0): Vg[H]", f2.seek(2,0))
print("Session 2 Reading... VgH[] -> []", f2.readline())
print("Session 6 seek(5,0): 6lRxh[S]m", f6.seek(5,0))
print("Session 6 Reading... 6lRxhSm[] -> []", f6.readline())
print("Session 7 seek(1,0): 7[]", f7.seek(1,0))
print("Session 7 Writing 'vQUEKD': 7vQUEKD[]", f7.write(b'vQUEKD'))
print("Session 7 seek(7,0): 7vQUEKD[]", f7.seek(7,0))
print("Session 7 Writing 'qgYGywAvTb': 7vQUEKDqgYGywAvTb[]", f7.write(b'qgYGywAvTb'))
print("Session 6 seek(0,0): [6]lRxhSm", f6.seek(0,0))
print("Session 6 Writing 'QEAyaDc': QEAyaDc[]", f6.write(b'QEAyaDc'))
print("Session 7 seek(-4,2): 7vQUEKDqgYGyw[A]vTb", f7.seek(-4,2))
print("Session 7 Writing 'hwHdBGeMYF': 7vQUEKDqgYGywhwHdBGeMYF[]", f7.write(b'hwHdBGeMYF'))
print("Session 2 seek(2,0): Vg[H]", f2.seek(2,0))
print("Session 2 Writing 'dQrgnlOf': VgdQrgnlOf[]", f2.write(b'dQrgnlOf'))
print("Session 6 seek(3,0): QEA[y]aDc", f6.seek(3,0))
print("Session 6 Reading... QEAyaDc[]", f6.readline())
print("Session 7 seek(23,0): 7vQUEKDqgYGywhwHdBGeMYF[]", f7.seek(23,0))
print("Session 7 Reading... 7vQUEKDqgYGywhwHdBGeMYF[]", f7.readline())
print("Session 5 seek(0,2): 5PQhLRe[]", f5.seek(0,2))
print("Session 5 Writing 'aiybPCnzO': 5PQhLReaiybPCnzO[]", f5.write(b'aiybPCnzO'))

print("Session 4 seek(3,0): 4QD[U]", f4.seek(3, 0))
print("Session 4 Writing 'dwPrG': 4QDdwPrG[]", f4.write(b'dwPrG'))

print("Session 5 seek(-14,2): 5P[Q]hLReaiybPCnzO", f5.seek(-14,2))
print("Session 5 Writing 'CNEVgX': 5PCNEVgX[i]ybPCnzO", f5.write(b'CNEVgX'))
print("Session 0 seek(0,2): 0[]", f0.seek(0,2))
print("Session 0 Writing 'NzI': 0NzI[]", f0.write(b'NzI'))
print("Session 3 seek(0,0): [3]wbR", f3.seek(0,0))
print("Session 3 Reading... 3wbR[]", f3.readline())


print("Session 4 seek(5,0): 4QDdw[P]rG", f4.seek(5, 0))
print("Session 4 read ... should be PrG", f4.readline())


