import os


fd0 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd1 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd2 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd3 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd4 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd5 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd6 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd7 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd8 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
fd9 = os.open("/dev/solution_node", os.O_RDWR | os.O_NOCTTY)
f0 = open(fd0, "wb+", buffering=0)
f1 = open(fd1, "wb+", buffering=0)
f2 = open(fd2, "wb+", buffering=0)
f3 = open(fd3, "wb+", buffering=0)
f4 = open(fd4, "wb+", buffering=0)
f5 = open(fd5, "wb+", buffering=0)
f6 = open(fd6, "wb+", buffering=0)
f7 = open(fd7, "wb+", buffering=0)
f8 = open(fd8, "wb+", buffering=0)
f9 = open(fd9, "wb+", buffering=0)

print("Session 3 Testing that first read returns valid sid...", f3.read())
print("Session 7 Testing that first read returns valid sid...", f7.read())
print("Session 6 Testing that first read returns valid sid...", f6.read())
print("Session 2 Testing that first read returns valid sid...", f2.read())
print("Session 9 Testing that first read returns valid sid...", f9.read())
print("Session 8 Testing that first read returns valid sid...", f8.read())
print("Session 4 Testing that first read returns valid sid...", f4.read())
print("Session 1 Testing that first read returns valid sid...", f1.read())
print("Session 0 Testing that first read returns valid sid...", f0.read())
print("Session 5 Testing that first read returns valid sid...", f5.read())
f0.seek(-1, 2)
print(f0.read())
f0.write(b"Hello World")
f0.seek(0, 0)
print(f0.read())
